config/routes.rb
ResReview::Application.routes.draw do

  get "homepages/index"
  get "homepages/about_us"
  get "homepages/topten"
  devise_for :users, :path_names => {:sign_in => "login", :sign_out => "logout"}, :path => "d"
  resources :users, :only => [:index,:show,:edit,:update,:destroy]
  
  resources :restaurants do
    member do
      get 'rating_average'
    end

    collection do
      get 'manage_review'
    end

  end

  
  resources :restaurant_categories,:except => [:show,:edit,:update]
  resources :locates,:except => [:show,:edit,:update]

  resources :images,:except => [:index,:show]
  resources :menus,:except => [:index,:show]
  resources :comments ,:except => [:index,:show]
  

  

   root 'homepages#index'

  

end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :user

	belongs_to :restaurant
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :update, :destroy]

  # GET /comments
  # GET /comments.json
  # def index
  #   @comments = Comment.all
  # end

  # GET /comments/1
  # GET /comments/1.json
  # def show
  # end

  # GET /comments/new
  def new
    @comment = Comment.new
    authorize! :new, @comment
  end

  # GET /comments/1/edit
  def edit
    @comment = Comment.find(params[:cc])
    redirect_to root_path if @comment.user_id != current_user.id && current_user.role != "admin"
    authorize! :new, @comment
    @comment.update(:comment => params[:comment])
    respond_to do |format|
      format.html { redirect_to restaurant_path(params[:restaurant_id]), notice: 'Comment was successfully updated.' }
    end
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = Comment.new(comment_params)
    authorize! :new, @comment
    respond_to do |format|
      if @comment.save
        format.html { redirect_to restaurant_path(params[:comment][:restaurant_id]), notice: 'Comment was successfully created.' }
        format.json { render action: 'show', status: :created, location: @comment }
      else
        format.html { render action: 'new' }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    authorize! :new, @comment
    redirect_to root_path if @comment.user_id != current_user.id && current_user.role != "admin"
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to restaurant_path(params[:comment][:restaurant_id]), notice: 'Comment was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    authorize! :new, @comment
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to restaurant_path(params[:restaurant_id]) , notice: 'Comment was successfully deleted.'}
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:comment, :user_id, :restaurant_id,:id,:cc)
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_form.html.erb
<%= form_for(@comment) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :comment %><br>
    <%= f.text_field :comment %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :restaurant_id %><br>
    <%= f.number_field :restaurant_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<h1>Listing comments</h1>

<table>
  <thead>
    <tr>
      <th>Comment</th>
      <th>User</th>
      <th>Restaurant</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.comment %></td>
        <td><%= comment.user_id %></td>
        <td><%= comment.restaurant_id %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New comment</h1>

<%= render 'form' %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Comment:</strong>
  <%= @comment.comment %>
</p>

<p>
  <strong>User:</strong>
  <%= @comment.user_id %>
</p>

<p>
  <strong>Restaurant:</strong>
  <%= @comment.restaurant_id %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>