config/routes.rb
ResReview::Application.routes.draw do

  get "homepages/index"
  get "homepages/about_us"
  get "homepages/topten"
  devise_for :users, :path_names => {:sign_in => "login", :sign_out => "logout"}, :path => "d"
  resources :users, :only => [:index,:show,:edit,:update,:destroy]
  
  resources :restaurants do
    member do
      get 'rating_average'
    end

    collection do
      get 'manage_review'
    end

  end

  
  resources :restaurant_categories,:except => [:show,:edit,:update]
  resources :locates,:except => [:show,:edit,:update]

  resources :images,:except => [:index,:show]
  resources :menus,:except => [:index,:show]
  resources :comments ,:except => [:index,:show]
  

  

   root 'homepages#index'

  

end

app/controllers/homepages_controller.rb
class HomepagesController < ApplicationController
	layout "homepage"
  def index
  end

  def about_us
  end

  def topten
  	@restaurants = Restaurant.where("total != 0.0").order("total DESC").limit(10)
  end
  
end

app/helpers/homepages_helper.rb
module HomepagesHelper
end

app/views/homepages/about_us.html.erb
<div class="container top_margin full_size">
	<div class="row full_size">
		<div class="span12 full_size">
			<div class="span3 span_nav">
				<%= render template: 'layouts/navbar' %>
			</div>
			<div class="span9 remain_span">
				<div style="text-align:center"><%= image_tag "aboutus.jpg" %></div>
			</div>
		</div>
	</div>
</div>





<script>
	   $(document).ready(function() {
        	$('body').css('background-image', 'url(/assets/spoon.jpg)');
    	});
</script>

app/views/homepages/index.html.erb
<div align="center" class="homepage_layout">
            <div class="content">
                <ul class="bmenu">
                    <li><%= link_to "Reviews", restaurants_path %></li>
                    <li><%= link_to "Top 10", homepages_topten_path %></li>
                    <% if can? :index, User %>   
                      <li><%= link_to "Manage Users", users_path %></li>
                    <% end %>
                    <li><%= link_to "Manage Reviews",  manage_review_restaurants_path %></li>
                    <% if can? :manage, RestaurantCategory %>
                      <li><%= link_to "Resturant Categories", restaurant_categories_path %></li>
                    <% end %>
                    <li><%= link_to "About us", homepages_about_us_path %></li>
                </ul>

            </div>
        <link href='http://fonts.googleapis.com/css?family=Josefin+Slab' rel='stylesheet' type='text/css' />
  </div>

app/views/homepages/topten.html.erb
	<div class="container top_margin full_size">
		<div class="row full_size">
			<div class="span12 full_size">
				<div class="span3 span_nav">
					<%= render template: 'layouts/navbar' %>
				</div>
				<div class="span9 remain_span">
					<div class="mg">
						<%= image_tag "topten.png",:width => '180', :class => "top_ten_head_img"%>
						<% count = 0 %>
						<% @restaurants.each do |restaurant| %>
						<!-- big -->
						<% if count == 0 %>
						<div class="mg-pic-right">
							<div class= 'oval-bg-bigsize mg-oval-bg-size' style="position:absolute;" >
								<div class="oval-bigsize img-resize-bigsize mg-oval-bigsize ">
									<% if restaurant.images.first %>
										<%= image_tag restaurant.images.first.image %>
									<% else %>
										<%= image_tag "nopicturebig.jpg" %>
									<% end %>
								</div>	
							</div>
						</div>
									

						<div class="box-bigsize">
							
							<div class="name-link-bigsize">
								<%= image_tag "one.png",:width => '150' %>&nbsp;&nbsp;
								<%=	link_to  restaurant.name , {:action => 'show', :controller => 'restaurants',:id => restaurant.id },{:class => 'color-link'} %>
								&nbsp;&nbsp
								Post by <%= link_to restaurant.user.user_name,user_path(restaurant.user_id) %>
								<hr>

							</div>
							
						</div>
						
						<% end %>


						<% if count == 1 %>
						<!-- medium-left -->
						<div class="mg-pic-left">
							<div class= 'oval-bg-medium mg-oval-bg-medium'style="position:absolute;" >
								<div class="oval-medium img-resize-medium mg-oval-medium ">
									<% if restaurant.images.first %>
										<%= image_tag restaurant.images.first.image %>
									<% else %>
										<%= image_tag "nopicturemedium.jpg" %>
									<% end %>
								</div>	
							</div>
						</div>
						<div class="mg-box-right">
							<div class="box-bigsize">
								<div class="name-link-medium">
									<%= image_tag "two.png",:width => '150' %>&nbsp;&nbsp;<%=	link_to  restaurant.name , {:action => 'show', :controller => 'restaurants',:id => restaurant.id },{:class => 'color-link'} %>
										&nbsp;&nbsp
									Post by <%= link_to restaurant.user.user_name,user_path(restaurant.user_id) %>
									<hr>
								</div>
							</div>
						</div> 
						
						<% end %>

						<% if count == 2 %>
						<!-- medium-right -->
						<div class="mg-pic-right">
							<div class= 'oval-bg-medium mg-oval-bg-medium'style="position:absolute;" >
								<div class="oval-medium img-resize-medium mg-oval-medium ">
									<% if restaurant.images.first %>
										<%= image_tag restaurant.images.first.image %>
									<% else %>
										<%= image_tag "nopicturemedium.jpg" %>
									<% end %>
								</div>	
							</div>
						</div>

						<div class="box-bigsize">
							<div class="name-link-medium">
								<%= image_tag "three.png",:width => '125' %>&nbsp;&nbsp;<%=	link_to  restaurant.name , {:action => 'show', :controller => 'restaurants',:id => restaurant.id },{:class => 'color-link'} %>
								&nbsp;&nbsp
								Post by <%= link_to restaurant.user.user_name,user_path(restaurant.user_id) %>
								<hr>
							</div>
						</div>

						<% end %>

						<% if count == 3 %>
						<!-- small-left -->
						<div class="mg-pic-left">
							<div class= 'oval-bg-small mg-oval-bg-small' style="position:absolute;">
								<div class="oval-small img-resize-small mg-oval-small ">
									<% if restaurant.images.first %>
										<%= image_tag restaurant.images.first.image %>
									<% else %>
										<%= image_tag "nopicture.jpg" %>
									<% end %>
								</div>	
							</div>
						</div>	
						<div class="mg-box-right">
							<div class="box-bigsize">
								<div class="name-link-small">
									<%= image_tag "four.png",:width => '125' %>&nbsp;&nbsp;&nbsp;&nbsp;<%=	link_to  restaurant.name , {:action => 'show', :controller => 'restaurants',:id => restaurant.id },{:class => 'color-link'} %>
									&nbsp;&nbsp
									Post by <%= link_to restaurant.user.user_name,user_path(restaurant.user_id) %>
									<hr>
								</div>
							</div>
						</div>
						
						<% end %>

						<% if count == 4 %>
						<!-- small-right -->
						<div class="mg-pic-right">
							<div class= 'oval-bg-small mg-oval-bg-small' style="position:absolute;">
								<div class="oval-small img-resize-small mg-oval-small ">
									<% if restaurant.images.first %>
										<%= image_tag restaurant.images.first.image %>
									<% else %>
										<%= image_tag "nopicture.jpg" %>
									<% end %>
								</div>	
							</div>
						</div>	
						
						<div class="box-bigsize">
							<div class="name-link-small">
								<%= image_tag "five.png",:width => '125' %>&nbsp;&nbsp;&nbsp;&nbsp;<%=	link_to  restaurant.name , {:action => 'show', :controller => 'restaurants',:id => restaurant.id },{:class => 'color-link'} %>
								&nbsp;&nbsp
								Post by <%= link_to restaurant.user.user_name,user_path(restaurant.user_id) %>
								<hr>
							</div>
						</div>
						
						<% end %>


						<% if count == 5 %>
						<!-- small-left -->
						<div class="mg-pic-left">
							<div class= 'oval-bg-small mg-oval-bg-small' style="position:absolute;">
								<div class="oval-small img-resize-small mg-oval-small ">
									<% if restaurant.images.first %>
										<%= image_tag restaurant.images.first.image %>
									<% else %>
										<%= image_tag "nopicture.jpg" %>
									<% end %>
								</div>	
							</div>
						</div>	
						<div class="mg-box-right">
							<div class="box-bigsize">
								<div class="name-link-small">
									<%= image_tag "six.png",:width => '125' %>&nbsp;&nbsp;&nbsp;&nbsp;<%=	link_to  restaurant.name , {:action => 'show', :controller => 'restaurants',:id => restaurant.id },{:class => 'color-link'} %>
									&nbsp;&nbsp
									Post by <%= link_to restaurant.user.user_name,user_path(restaurant.user_id) %>
									<hr>
								</div>
							</div>
						</div>
						
						<% end %>

						<% if count == 6 %>
						<!-- small-right -->
						<div class="mg-pic-right">
							<div class= 'oval-bg-small mg-oval-bg-small' style="position:absolute;">
								<div class="oval-small img-resize-small mg-oval-small ">
									<% if restaurant.images.first %>
										<%= image_tag restaurant.images.first.image %>
									<% else %>
										<%= image_tag "nopicture.jpg" %>
									<% end %>
								</div>	
							</div>
						</div>	
						
						<div class="box-bigsize">
							<div class="name-link-small">
								<%= image_tag "seven.png",:width => '125' %>&nbsp;&nbsp;&nbsp;&nbsp;<%=	link_to  restaurant.name , {:action => 'show', :controller => 'restaurants',:id => restaurant.id },{:class => 'color-link'} %>
								&nbsp;&nbsp
								Post by <%= link_to restaurant.user.user_name,user_path(restaurant.user_id) %>
								<hr>
							</div>
						</div>
						
						<% end %>


						<% if count == 7 %>
						<!-- small-left -->
						<div class="mg-pic-left">
							<div class= 'oval-bg-small mg-oval-bg-small' style="position:absolute;">
								<div class="oval-small img-resize-small mg-oval-small ">
									<% if restaurant.images.first %>
										<%= image_tag restaurant.images.first.image %>
									<% else %>
										<%= image_tag "nopicture.jpg" %>
									<% end %>
								</div>	
							</div>
						</div>	
						<div class="mg-box-right">
							<div class="box-bigsize">
								<div class="name-link-small">
									<%= image_tag "eight.png",:width => '125' %>&nbsp;&nbsp;&nbsp;&nbsp;<%=	link_to  restaurant.name , {:action => 'show', :controller => 'restaurants',:id => restaurant.id },{:class => 'color-link'} %>
									&nbsp;&nbsp
									Post by <%= link_to restaurant.user.user_name,user_path(restaurant.user_id) %>
									<hr>
								</div>
							</div>
						</div>

						<% end %>

						<% if count == 8 %>
						<!-- small-right -->
						<div class="mg-pic-right">
							<div class= 'oval-bg-small mg-oval-bg-small' style="position:absolute;">
								<div class="oval-small img-resize-small mg-oval-small ">
									<% if restaurant.images.first %>
										<%= image_tag restaurant.images.first.image %>
									<% else %>
										<%= image_tag "nopicture.jpg" %>
									<% end %>
								</div>	
							</div>
						</div>	
						
						<div class="box-bigsize">
							<div class="name-link-small">
								<%= image_tag "nine.png",:width => '125' %>&nbsp;&nbsp;&nbsp;&nbsp;<%=	link_to  restaurant.name , {:action => 'show', :controller => 'restaurants',:id => restaurant.id },{:class => 'color-link'} %>
								&nbsp;&nbsp
								Post by <%= link_to restaurant.user.user_name,user_path(restaurant.user_id) %>
								<hr>
							</div>
						</div>
						
						<% end %>


						<% if count == 9 %>
						<!-- small-left -->
						<div class="mg-pic-left">
							<div class= 'oval-bg-small mg-oval-bg-small' style="position:absolute;">
								<div class="oval-small img-resize-small mg-oval-small ">
									<% if restaurant.images.first %>
										<%= image_tag restaurant.images.first.image %>
									<% else %>
										<%= image_tag "nopicture.jpg" %>
									<% end %>
								</div>	
							</div>
						</div>	
						<div class="mg-box-right">
							<div class="box-bigsize">
								<div class="name-link-small">
									<%= image_tag "ten.png",:width => '125' %>&nbsp;&nbsp;<%=	link_to  restaurant.name , {:action => 'show', :controller => 'restaurants',:id => restaurant.id },{:class => 'color-link'} %>
									&nbsp;&nbsp
									Post by <%= link_to restaurant.user.user_name,user_path(restaurant.user_id) %>
									<hr>
								</div>
							</div>
						</div>
						
						<% end %>


						<% count = count +1 %>
						<%end%>
					</div>
				</div>
			</div>
		</div><!--/row-->
	</div> <!-- /container -->



<script>
	   $(document).ready(function() {
        	$('body').css('background-image', 'url(/assets/spoon.jpg)');
    	});
</script>