config/routes.rb
ResReview::Application.routes.draw do

  get "homepages/index"
  get "homepages/about_us"
  get "homepages/topten"
  devise_for :users, :path_names => {:sign_in => "login", :sign_out => "logout"}, :path => "d"
  resources :users, :only => [:index,:show,:edit,:update,:destroy]
  
  resources :restaurants do
    member do
      get 'rating_average'
    end

    collection do
      get 'manage_review'
    end

  end

  
  resources :restaurant_categories,:except => [:show,:edit,:update]
  resources :locates,:except => [:show,:edit,:update]

  resources :images,:except => [:index,:show]
  resources :menus,:except => [:index,:show]
  resources :comments ,:except => [:index,:show]
  

  

   root 'homepages#index'

  

end

app/models/image.rb
class Image < ActiveRecord::Base
	belongs_to :restaurant

	mount_uploader :image, ImageUploader
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  
  before_action :set_image, only: [:show, :edit, :update, :destroy]

  # GET /images
  # GET /images.json
  # def index
  #   @images = Image.all
  # end

  # GET /images/1
  # GET /images/1.json
  # def show
  # end

  # GET /images/new
  def new
    @image = Image.new
    authorize! :new, @image
  end

  # GET /images/1/edit
  def edit
    authorize! :edit, @image
  end

  # POST /images
  # POST /images.json
  def create
    @image = Image.new(image_params)
    authorize! :create, @image
    respond_to do |format|
      if @image.save
        format.html { redirect_to @image, notice: 'Image was successfully created.' }
        format.json { render action: 'show', status: :created, location: @image }
      else
        format.html { render action: 'new' }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /images/1
  # PATCH/PUT /images/1.json
  def update
    authorize! :update, @image
    respond_to do |format|
      if @image.update(image_params)
        format.html { redirect_to @image, notice: 'Image was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /images/1
  # DELETE /images/1.json
  def destroy
    authorize! :destroy, @image
    @image.destroy
    respond_to do |format|
      format.html { redirect_to images_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_image
      @image = Image.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def image_params
      params.require(:image).permit(:image, :description, :restaurant_id)
    end
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/views/images/_form.html.erb
<%= form_for(@image) do |f| %>
  <% if @image.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@image.errors.count, "error") %> prohibited this image from being saved:</h2>

      <ul>
      <% @image.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :image %><br>
    <%= f.file_field :image %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :restaurant_id %><br>
    <%= f.number_field :restaurant_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/images/edit.html.erb
<h1>Editing image</h1>

<%= render 'form' %>

<%= link_to 'Show', @image %> |
<%= link_to 'Back', images_path %>

app/views/images/index.html.erb
<h1>Listing images</h1>

<table>
  <thead>
    <tr>
      <th>Image</th>
      <th>Description</th>
      <th>Restaurant</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @images.each do |image| %>
      <tr>
        <td><%= image_tag(image.image, height: '32', width: '32') %></td>
        <td><%= image.description %></td>
        <td><%= image.restaurant_id %></td>
        <td><%= link_to 'Show', image %></td>
        <td><%= link_to 'Edit', edit_image_path(image) %></td>
        <td><%= link_to 'Destroy', image, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Image', new_image_path %>

app/views/images/new.html.erb
<h1>New image</h1>

<%= render 'form' %>

<%= link_to 'Back', images_path %>

app/views/images/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Image:</strong>
  <%= @image.image %>
</p>

<p>
  <strong>Description:</strong>
  <%= @image.description %>
</p>

<p>
  <strong>Restaurant:</strong>
  <%= @image.restaurant_id %>
</p>

<%= link_to 'Edit', edit_image_path(@image) %> |
<%= link_to 'Back', images_path %>